#**Dictionary:**

*   A dictionary is a collection which is ordered (from Python 3.7 version), changeable and indexed.
*   Each item of a dictionary has a key:value pair .

In [ ]:
#Creation

#keys must be of any immutable data type - int, float, boolean, string, tuple

new_dict = {} #empty dictionary
#print(new_dict)

dict1 = {4: 'Harry', 1: 'John', 2: 'Carol', 3: 'Moon'} #dictionary of Integer Keys
print(dict1) #ordered

dict2 = {'Name':'John', 'Courses': ['CSE111', 'PHY111'], 1: 'Dhaka', (101, 102): 23.5} #dictionary with mixed keys
#print(dict2)

In [8]:
#using built-in dict() function

fruits = dict({1: 'Mango', 2: 'Apple'})
#print(fruits)

# from sequence/iterable having each item as a pair 
#iterable - list, tuple

fruits2 = dict([(1, 'Lemon'), ('abc', ['Orange', 'Banana'])]) #first index of a pair will be key
print(fruits2)
fruits2['abc'][0] = 'Apple'
print(fruits2)
#using keyword arguments.
age_data = dict(Emma = 25, Luke = 23)
print(age_data)

{1: 'Lemon', 'abc': ['Orange', 'Banana']}
{1: 'Lemon', 'abc': ['Apple', 'Banana']}
{'Emma': 25, 'Luke': 23}

In [ ]:
#Accessing Elements from Dictionary

#no indexing, need to use KEYS

#using square bracket[key_name]
data = {'Harry': 25, 'Ron': 27, 123: 'bhul info'}
#print(data['Harry']) #put the key in third bracket, check the quote for string

#print(data['123']) #what's wrong??

#using get() method
print(data.get('Ron'))

#difference??
#print(data['Hermione']) #shows error for non-existing keys
#print(data.get('Hermione')) #returns None for non-existing keys

In [10]:
#duplicate keys are not possible

data = {'Harry': 25, 'Ron': 27, 123: 'bhul info'}
data ['Harry'] = 45 #replaced old values
data.update({'xyz': 123})

print(data)

{'Harry': 45, 'Ron': 27, 123: 'bhul info', 'xyz': 123}

In [11]:
#Update items

info = {'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}
print(info)
info['Name'] = 'Harry Potter' #update existing entry
print(info)
info['Player Type'] = 'Seeker' #new item will be added
print(info)

#using update function
info.update({'Age': 28, 'Place': 'Godric Hollow'})
print(info)

{'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}
{'Name': 'Harry Potter', 'Age': 23, 'School': 'Hogwarts'}
{'Name': 'Harry Potter', 'Age': 23, 'School': 'Hogwarts', 'Player Type': 'Seeker'}
{'Name': 'Harry Potter', 'Age': 28, 'School': 'Hogwarts', 'Player Type': 'Seeker', 'Place': 'Godric Hollow'}

In [15]:
#Remove Items

info2 = {'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts', 'House': 'Gryffinder'}

#using pop(key)
print(info2.pop('Age')) #remove a particular item and return value
#print(f"Age of {info2['Name']} is {info2.pop('Age')}") #comment the above line and check it
print(info2)

#using popitem()
print(info2.popitem()) #remove an item from end, return (key,value)

#using del
del info2['School']
print(info2)

#clear() removes all items
info2.clear()
print(info2)

#delete the entire dictionary
del info2
#print(info2) #error - it doesn't exist anymore

23
{'Name': 'Harry', 'School': 'Hogwarts', 'House': 'Gryffinder'}
('House', 'Gryffinder')
{'Name': 'Harry'}
{}

In [17]:
#Copy a dictioanry

student1 = {'Name':'Aegon', 'Age': 15, 'House': 'Targaryen'}
student2 = student1.copy() #a brand new dictionary


student2['Age'] = 25
print(student1)
print(student2)

{'Name': 'Aegon', 'Age': 15, 'House': 'Targaryen'}
{'Name': 'Aegon', 'Age': 25, 'House': 'Targaryen'}

In [18]:
#Just for checking

student1 = {'Name':'Aegon', 'Age': 15, 'House': 'Targaryen'}
student2 = student1 #assigning the reference, both referer to same dictionary
print(student2)

student2['Age'] = 25 
print(student1) 
print(student2)

{'Name': 'Aegon', 'Age': 15, 'House': 'Targaryen'}
{'Name': 'Aegon', 'Age': 25, 'House': 'Targaryen'}
{'Name': 'Aegon', 'Age': 25, 'House': 'Targaryen'}

In [26]:
#Nested Dictionary

mystudents = {
"student1" : {
"name" : "Emil",
"year" : 2004
},
"student2" : {
"name" : "Tobias",
"year" : 2007
},
"student3" : {
"name" : "Linus",
"year" : 2011,
(1, 'complex'):[1,2,{3:['Never Give up']}]
}
}

#print(mystudents)
#print(mystudents['student1']['name'])
#print(mystudents['student2']['name'])
#print(mystudents["student3"][(1, 'complex')][-1][3][0])

Never Give up

In [32]:
info2 = {'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}
print(info2.keys())
print(list(info2.keys()))
print(info2.values())
print(info2.items()) #returns key-value pair
list1 = list(info2.items())
print(list1)

dict_keys(['Name', 'Age', 'School'])
['Name', 'Age', 'School']
dict_values(['Harry', 23, 'Hogwarts'])
dict_items([('Name', 'Harry'), ('Age', 23), ('School', 'Hogwarts')])
[('Name', 'Harry'), ('Age', 23), ('School', 'Hogwarts')]

In [35]:
#Iterating dictionary (Loop):

squares = {1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
for i in squares:
    print(squares[i], end = " ") #just the values

print('\n')

#print values and keys of dictionary
for key, value in squares.items():
    print(key,":", value, end = "\n")

#Assigning value with for loop
new_squares = {}
for x in range(10):
    new_squares[x] = x*x
print(new_squares)

# Assigning values with if conditional (Dictionary Comprehension)
even_squares = {x: x*x for x in range(10) if x % 2 == 0} #{key: value as expression => for iterator in iterable => if condition}
print(even_squares)

#more on dictionary comporehension https://www.programiz.com/python-programming/dictionary-comprehension

1 9 25 49 81

1 : 1
3 : 9
5 : 25
7 : 49
9 : 81
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}
{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

In [36]:
#Membership Test

# Membership Test for Dictionary Keys
info3 = {'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}

print('Name' in info3)
print('House' in info3)
print('Harry' in info3) #Membership test checks for key only,not value

True
False
False

In [38]:
#Dictionary Methods

#len(dict)
info4 = {'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}
print(len(info4)) #number of items = length


#str(dict)
string1 = str(info4) #Produces a printable string representation of a dictionary
print(string1)
print(type(string1))

#fromkeys(sequence ,v)

list1 = [1,2,3]
val = 10.5
dict2 = dict.fromkeys(list1, val) #Returns a new dictionary with keys from sequence and value equal to v
print(dict2)

#sorted(dictionary)

dict5 = {4:'d', 2:'b', 1: 'a', 3:'c' }
s = sorted(dict5, reverse = True) #sorted list of keys
print(dict5)
print(s)

3
{'Name': 'Harry', 'Age': 23, 'School': 'Hogwarts'}
<class 'str'>
{1: 10.5, 2: 10.5, 3: 10.5}
{4: 'd', 2: 'b', 1: 'a', 3: 'c'}
[4, 3, 2, 1]

# **Functions**
A function is a block of code which only runs when it is called.

```
A function has 4 parts.
*   Name
*   Parameter
*   Body
*   Return Statement
```


```
There can be 4 types of functions.
*   User-defined
*   Built-In
*   Lambda
*   Recursive

```

In [ ]:
#Built-In

#input() , print(), range(), len()

In [ ]:
#User-defined Functions

#two types - void & fruitful
#void function doesn't return anything
#fruitful function return some value

'''
x = 10
x = x + 2
x = x*2
x = x + 3
x = x*3
x = x + 10
x = x*10
x = x + 90
x = x*90

print(x) #output = 90000
'''

#To avoid same instructions over and over

def calculate(x, y): #parameters
    x = x + y
    x = x*y
    return x

x = calculate(10, 2) #argumenmts
x = calculate(x, 3)
x = calculate(x, 10)
x = calculate(x, 90)
print(x)

In [ ]:
#Number of Args

def my_function(name, place):

    print(name+" goes to "+place)

my_function("Alex", "Shopping Complex")
#my_function("Alex") #error - 2 args needed

In [40]:
#Unknown Number of Args => *args

def my_function(*kids):
    print(kids)
    print(type(kids))
    print("The first child is "+ kids[0])

my_function("Alice", "Bob", "Carrol")

('Alice', 'Bob', 'Carrol')
<class 'tuple'>
The first child is Alice

In [41]:
#keyword args

def my_function(child3, child2, child1):
    print("The youngest child is " + child3) #order doesn't matter

my_function(child1 = "David", child2 = "Daniel", child3 = "Nicolai")

The youngest child is Nicolai

In [ ]:
# **kwargs for variable number of keyword arguments
 
def myFun(**kwargs):
    for key, value in kwargs.items():
        print (key, value)
 

myFun(first ='Geeks', mid ='for', last='Geeks') #notice the order

In [ ]:
#using the *args and **kwargs at the same time

def myFun(*args,**kwargs):
    print("args: ", args)
    print("kwargs: ", kwargs)
 
 
# Now we can use both *args ,**kwargs
# to pass arguments to this function :
myFun('geeks','for','geeks',first="Geeks",mid="for",last="Geeks")
#myFun(first="Geeks", 'geeks','for','geeks',first="Geeks",mid="for",last="Geeks") #error

In [42]:
#Default arguments

def storeInfo(name, id = 1): #default arg should be come later
    print(f"{name}'s id is {id}")

storeInfo('Harry')
storeInfo('Harry', 1000)

Harry's id is 1
Harry's id is 1000

In [43]:
#Return 

def sum(x, y):
    return x + y
result = sum(10, 20)
print(result)

#example-2 ---------------------------------
def values(x, y, z = 123):
    return x, y, z #multple values return as tuple

print(values(1,2)) #check the type

#example 3
def fun():
    x = 10
print(fun()) #doesn't return anything so None

30
(1, 2, 123)
None

In [ ]:
def function2(a_string):
    name, id = a_string.split('/')
    return name,id

tup = function2('John/101')
print(tup[0], tup[1])
name, id = function2('Barney/10101')
print(name, id)

In [ ]:
#Pass keyword

#if function doesn't have any body use pass to avoid error
def incompletefunction():
    pass
incompletefunction()

In [ ]:
#lambda Function

def average(x, y):
    return (x + y)/2 #single expression
print(average(4, 3))

#using lambda func
print((lambda x, y: (x + y)/2)(4, 3))

In [ ]:
#recursive function

def recursiveAdd(n):
    if n == 1:
        return 1
    else:
        return n + recursiveAdd(n-1)

print(recursiveAdd(3))



```
recursiveAdd(3)         #1st call with 3
3 + recursiveAdd(2)     #2nd call with 2
3 + 2 + recursiveAdd(1) #3rd call with 1
3 + 2 + 1               #return from 3rd call with n = 1
3 + 3                   #return from 2nd call
6                       #return from 1st call

```