In [ ]:
class Nokia:
    pass

n1 = Nokia()
print(n1)

n2 = Nokia()
print(n2)
n3 = Nokia()

<__main__.Nokia object at 0x7f51e0bab910>
<__main__.Nokia object at 0x7f51da861c90>

In [ ]:
class Nokia:
    pass

nok1 = Nokia()
#print(nok1.color)
nok1.color = 'Ash' #Instance Variable
nok1.ID = 1001

print(nok1.color, nok1.ID)
print(nok1)

nok2 = Nokia()
nok2.color = 'Black'
nok2.ID = 2001
nok2.model = 'Nokia-1100'
print(nok2.color, nok2.ID, nok2.model)

#print(nok1.color, nok1.ID, nok1.model)

print(nok1 == nok2)

Ash 1001
<__main__.Nokia object at 0x7fc00fece150>
Black 2001 Nokia-1100
False

In [ ]:
class Student:
    def __init__(self): #constructor/builder/worker method
        print('Hello there!')
        print(self)
        self.name = 'Default' #instance variables
        self.id = 'Jani na'
        self.dept = 'Jani na'
s1 = Student()
print(s1)
print(s1.name, s1.id, s1.dept)
s1.name = 'Harry'
s1.id = 123
s1.dept = 'CSE'
print(s1.name, s1.id, s1.dept)
s2 = Student()
# s2.name = 'Ron'
# s2.id = 129
# s2.dept = 'CSE'

Hello there!
<__main__.Student object at 0x7fc00f327050>
<__main__.Student object at 0x7fc00f327050>
Default Jani na Jani na
Harry 123 CSE
Hello there!
<__main__.Student object at 0x7fc00f3a4f10>

In [ ]:
class Student:
    def __init__(self, n, i, dep): #constructor/builder/worker method
        #print('Hello there!')
        #print(self)
        self.name = n
        self.id = i
        self.dept = dep

s1 = Student('Harry', 123, 'CSE')
print(s1.name, s1.id, s1.dept)
s2 = Student('Rafeed', 120, 'EEE')
print(s2.name, s2.id, s2.dept)

Harry 123 CSE
Rafeed 120 EEE