In [ ]:
class Student:
    def __init__(self, name, id, dept): #constructor/builder/worker method
        self.name = name
        self.id = id
        self.dept = dept
        self.varsity = 'Bracu' #instance var with default value
    def showData(self):
        
         #print(self) #write self as convention 
         print(self.name)
         print(self.id)
         print(self.dept)
         print(self.varsity) 

s1 = Student('Harry', 123, 'CSE')
s1.showData()
#print('s1', s1)
#print(s1.name, s1.id, s1.dept)
print('------------------------')
s2 = Student('Rafeed', 120, 'EEE')
s2.showData()
#print(s2.name, s2.id, s2.dept)

------------------------

In [ ]:
class Student:
    def __init__(self, name, id, dept): 
        self.name = name
        self.id = id
        self.dept = dept
        self.varsity = 'Bracu' 
        self.courses = []
    def addCourses(self, course = 'CSE091'):
        self.courses.append(course)
    
    def showData(self):
        print(self.name, self.id, self.dept, self.varsity)
        print(self.courses)
          
s1 = Student('Harry', 123, 'CSE')
s1.showData()
s1.addCourses('CSE111')
s1.addCourses('PHY111')
s1.addCourses('CSE230')
s1.showData()
print('------------------------')
s2 = Student('Rafeed', 120, 'EEE')
s2.showData()
s2.addCourses()
s2.showData()

Harry 123 CSE Bracu
[]
Harry 123 CSE Bracu
['CSE111', 'PHY111', 'CSE230']
------------------------
Rafeed 120 EEE Bracu
[]
Rafeed 120 EEE Bracu
['CSE091']

In [ ]:
class Student:
    def __init__(self, name, id, dept): 
        self.name = name
        self.id = id
        self.dept = dept
        self.varsity = 'Bracu' 
        self.courses = []
        self.books = []
    def addCourses(self, course = 'CSE091'):
        self.courses.append(course)
    def addBooks(self, *books):
        #print(books)
        for b in books:
            #print(b)
            self.books.append(b)

    def showData(self):
        print(self.name, self.id, self.dept, self.varsity)
        print(self.courses)
        print(self.books)
          
s1 = Student('Harry', 123, 'CSE')
#s1.showData()
s1.addCourses('CSE111')
s1.addCourses('PHY111')
s1.addCourses('CSE230')
#s1.showData()
s1.addBooks('CSE111 Boi', 'PHY111 Boi')
s1.addBooks('CSE230 Boi')
s1.showData()
print('------------------------')
s2 = Student('Rafeed', 120, 'EEE')
#s2.showData()
s2.addCourses()
s2.showData()

Harry 123 CSE Bracu
['CSE111', 'PHY111', 'CSE230']
['CSE111 Boi', 'PHY111 Boi', 'CSE230 Boi']
------------------------
Rafeed 120 EEE Bracu
['CSE091']
[]